### ISSUE TITLE
Failed to build on macOS 10.14.5

### ISSUE THREAD

**Issue by Yevgnen** [d12frosted/homebrew-emacs-plus#144]
Build failed with `brew install -v emacs-plus --without-spacemacs-icon --with-xwidgets --with-jansson --HEAD`, the logs are placed [here](https://gist.github.com/Yevgnen/8c8cd053a3a8acbd47503e339c6d5ad9).

**Comment by shuxiao9058** [comment]
this was because of emacs recent commit https://github.com/emacs-mirror/emacs/commit/b9ac4f815ebaa1acb0d045fe9583f665efa6f628

**Comment by Yevgnen** [comment]
Thanks for the information, I know little of `.c` and have no idea of that.

**Comment by pcr910303** [comment]
@Yevgnen Looks like this bug is fixed in commit 848ff94b45. Try rebuilding from HEAD :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Yevgnen** [comment]
Thanks for the information. Now I got another error of `HEAD-e8d1743`...😂


    clang   -Wno-switch -Wno-pointer-sign -Wno-string-plus-int -Wno-unknown-attributes -Wno-initializer-overrides -Wno-tautological-compare -Wno-tautological-constant-out-of-range-compare  -I. -I../src -I../lib -I. -I./../src -I./../lib    -g3 -O2 -o ebrowse ebrowse.c  ../lib/libgnu.a
    clang   -Wno-switch -Wno-pointer-sign -Wno-string-plus-int -Wno-unknown-attributes -Wno-initializer-overrides -Wno-tautological-compare -Wno-tautological-constant-out-of-range-compare  -I. -I../src -I../lib -I. -I./../src -I./../lib    -g3 -O2 hexl.c ../lib/libgnu.a  -o hexl
    emacsclient.c:261:11: error: use of undeclared identifier 'pwdlen'
          && (pwdlen = strnlen (pwd, bufsize_max)) < bufsize_max
              ^
    emacsclient.c:262:32: error: use of undeclared identifier 'pwdlen'
          && IS_DIRECTORY_SEP (pwd[pwdlen && IS_DEVICE_SEP (pwd[1]) ? 2 : 0])
                                   ^
    2 errors generated.
    make[1]: *** [emacsclient] Error 1
    make[1]: *** Waiting for unfinished jobs....

**Comment by d12frosted** [comment]
@Yevgnen lucky you are! :smile_cat:
